docker build -t agents . ;
docker run \
--name Twitter-$BOT_ID \
-e KEY=$TWITTER_CONSUMER_KEY \
-e SECRET=$TWITTER_CONSUMER_SECRET \
-e TOKEN=$TWITTER_ACCESS_TOKEN \
-e TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET \
-e SERVER_HOST=$SERVER_HOST \
-e SERVER_PORT=$SERVER_PORT \
-e USER_AGENT=$USER_AGENT \
-e TOR_PROXY=$TOR_PROXY
