docker build -t agents . ;
docker run \
--name Twitter-$BOT_ID \
-e BOT_ID = $BOT_ID \
-e TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY \
-e TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET \
-e TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN \
-e TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET \
-e SERVER_HOST=$SERVER_HOST \
-e SERVER_PORT=$SERVER_PORT \
-e USER_AGENT=$USER_AGENT \
-e TOR_PROXY=$TOR_PROXY
