version: '2.0'

services:
  bot:
    build: 
      context: ../../
      dockerfile: docker/bots/Dockerfile
    container_name: bot
    restart: always
    environment:
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

      BOT_ID: ${{ secrets.BOT_ID }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      TOKEN: ${{ secrets.TOKEN }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
