version: '3.0'

services:
  redis:
    image: redis
    container_name: bot_redis
    restart: always
    ports:
      - 6379:6379
  bot:
    image: docker.pkg.github.com/detiuaveiro/social-network-mining/bot
    container_name: bot
    network_mode: host
    depends_on:
      - redis
    env_file:
      - ~/PI_2020/env_vars/bot.env
