FROM python:3.7.3-alpine3.9

COPY requirements.txt /

# build dependencies, stored in a virtual package
RUN apk add --update --no-cache --virtual .build-dependencies \ 
	gcc \
	linux-headers \
	libc-dev \
	python3-dev \
	# runtime dependencies
	&& apk add --update --no-cache postgresql-dev \
	&& pip install -r requirements.txt \
	&& apk del .build-dependencies

COPY send.py /
COPY ./Enums /Enums
COPY ./Mongo /Mongo
COPY ./Postgres /Postgres
COPY ./Neo4j /Neo4j
COPY ./PDP /PDP
COPY ./PEP /PEP
COPY policy_api.py /
COPY settings.py /
COPY task.py /
COPY rabbitmq.py /

CMD [ "python", "-u", "rabbitmq.py" ]