# Generated by Django 2.1.7 on 2019-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=15, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('total_score', models.IntegerField(default=0)),
                ('total_voted', models.IntegerField(default=0)),
            ],
        ),
    ]
