# Generated by Django 2.2.10 on 2020-03-02 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('API_type', models.TextField()),
                ('filter', models.TextField()),
                ('name', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('bots', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('tweet_id', models.IntegerField(db_column='id')),
                ('user', models.TextField()),
                ('is_quote_status', models.BooleanField()),
                ('quoted_status_id', models.IntegerField(blank=True, null=True)),
                ('in_reply_to_screen_name', models.TextField(blank=True, null=True)),
                ('in_reply_to_user_id', models.IntegerField(blank=True, null=True)),
                ('in_reply_to_status_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tweets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='id')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('name', models.TextField()),
                ('screen_name', models.TextField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('profile_image_url_https', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
