# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install all dependencies
      run: |
          for r in $(find . | grep requirements.txt | grep code/backend/twitter); do
            echo $r
            pip install --user -r $r
          done
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 code/backend/twitter --count --select=E9,F63,F7,F82 --show-source --statistics
        # check all identation problems and stop the build if there is at least one
        # Adicionar o E402 quando o projeto estiver em estrutura de arvore
        identation_problems="E101,E111,E112,E113,E114,E115,E116,E121,E122,E123,E124,E125,E126,E127,E128,E129,E131,E133,E201,E202,E203,E211,E221,E222,E223,E224,E225,E226,E227,E228,E231,E241,E242,E251,E261,E262,E265,E266,E271,E272,E273,E274,E275,E301,E302,E303,E304,E305,E401,E501,E502,E701,E702,E703,E704,E711,E712,E713,E714,E721,E731,E741,E742,E743"
        flake8 code/backend/twitter --count --select=$identation_problems --show-source --statistics --max-complexity=10 --max-line-length=127
    #- name: Test with pytest
    #  run: |
    #    pip install pytest
    #    pytest
